export const SEND_SIGNUP_OTP_REQUEST = 'SEND_SIGNUP_OTP_REQUEST';
export const SEND_SIGNUP_OTP_SUCCESS = 'SEND_SIGNUP_OTP_SUCCESS';
export const SEND_SIGNUP_OTP_FAIL = 'SEND_SIGNUP_OTP_FAIL';

export const VERIFY_SIGNUP_OTP_REQUEST = 'VERIFY_SIGNUP_OTP_REQUEST';
export const VERIFY_SIGNUP_OTP_SUCCESS = 'VERIFY_SIGNUP_OTP_SUCCESS';
export const VERIFY_SIGNUP_OTP_FAIL = 'VERIFY_SIGNUP_OTP_FAIL';

export const SEND_LOGIN_OTP_REQUEST = 'SEND_LOGIN_OTP_REQUEST';
export const SEND_LOGIN_OTP_SUCCESS = 'SEND_LOGIN_OTP_SUCCESS';
export const SEND_LOGIN_OTP_FAIL = 'SEND_LOGIN_OTP_FAIL';

export const VERIFY_LOGIN_OTP_REQUEST = 'VERIFY_LOGIN_OTP_REQUEST';
export const VERIFY_LOGIN_OTP_SUCCESS = 'VERIFY_LOGIN_OTP_SUCCESS';
export const VERIFY_LOGIN_OTP_FAIL = 'VERIFY_LOGIN_OTP_FAIL';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

