// constants.js
export const SUBMIT_ISALLOW_REQ = 'SUBMIT_ISALLOW_REQ';
export const SUBMIT_ISALLOW_SUCCESS = 'SUBMIT_ISALLOW_SUCCESS';
export const SUBMIT_ISALLOW_FAIL = 'SUBMIT_ISALLOW_FAIL';


export const GET_LATEST_ISALLOW_REQ = 'GET_LATEST_ISALLOW_REQ';
export const GET_LATEST_ISALLOW_SUCCESS = 'GET_LATEST_ISALLOW_SUCCESS';
export const GET_LATEST_ISALLOW_FAIL = 'GET_LATEST_ISALLOW_FAIL';


export const FILL_LUCKYDRAW_REQ = 'FILL_LUCKYDRAW_REQ';
export const FILL_LUCKYDRAW_SUCCESS = 'FILL_LUCKYDRAW_SUCCESS';
export const FILL_LUCKYDRAW_FAIL = 'FILL_LUCKYDRAW_FAIL';

export const GET_APPLICATIONS_REQ = 'GET_APPLICATIONS_REQ';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_FAIL = 'GET_APPLICATIONS_FAIL';


export const GET_LUCKYDRAW_BY_ID_REQ = 'GET_LUCKYDRAW_BY_ID_REQ';
export const GET_LUCKYDRAW_BY_ID_SUCCESS = 'GET_LUCKYDRAW_BY_ID_SUCCESS';
export const GET_LUCKYDRAW_BY_ID_FAIL = 'GET_LUCKYDRAW_BY_ID_FAIL';

// actionTypes.js

// Constants for updating LuckyDraw status
export const UPDATE_LUCKYDRAW_STATUS_REQ = 'UPDATE_LUCKYDRAW_STATUS_REQ';
export const UPDATE_LUCKYDRAW_STATUS_SUCCESS = 'UPDATE_LUCKYDRAW_STATUS_SUCCESS';
export const UPDATE_LUCKYDRAW_STATUS_FAIL = 'UPDATE_LUCKYDRAW_STATUS_FAIL';


// Constants for fetching all lucky draws
export const GET_ALL_LUCKYDRAW_REQ = 'GET_ALL_LUCKYDRAW_REQ';
export const GET_ALL_LUCKYDRAW_SUCCESS = 'GET_ALL_LUCKYDRAW_SUCCESS';
export const GET_ALL_LUCKYDRAW_FAIL = 'GET_ALL_LUCKYDRAW_FAIL';
