// constants.js
export const SUBMIT_ISALLOW_REQ = 'SUBMIT_ISALLOW_REQ';
export const SUBMIT_ISALLOW_SUCCESS = 'SUBMIT_ISALLOW_SUCCESS';
export const SUBMIT_ISALLOW_FAIL = 'SUBMIT_ISALLOW_FAIL';


export const GET_LATEST_ISALLOW_REQ = 'GET_LATEST_ISALLOW_REQ';
export const GET_LATEST_ISALLOW_SUCCESS = 'GET_LATEST_ISALLOW_SUCCESS';
export const GET_LATEST_ISALLOW_FAIL = 'GET_LATEST_ISALLOW_FAIL';


export const FILL_LUCKYDRAW_REQ = 'FILL_LUCKYDRAW_REQ';
export const FILL_LUCKYDRAW_SUCCESS = 'FILL_LUCKYDRAW_SUCCESS';
export const FILL_LUCKYDRAW_FAIL = 'FILL_LUCKYDRAW_FAIL';

export const GET_APPLICATIONS_REQ = 'GET_APPLICATIONS_REQ';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_FAIL = 'GET_APPLICATIONS_FAIL';


// CompanyFill action types
export const GET_COMPANYFILL_REQ = 'GET_COMPANYFILL_REQ';
export const GET_COMPANYFILL_SUCCESS = 'GET_COMPANYFILL_SUCCESS';
export const GET_COMPANYFILL_FAIL = 'GET_COMPANYFILL_FAIL';



export const GET_LUCKYDRAW_BY_ID_REQ = 'GET_LUCKYDRAW_BY_ID_REQ';
export const GET_LUCKYDRAW_BY_ID_SUCCESS = 'GET_LUCKYDRAW_BY_ID_SUCCESS';
export const GET_LUCKYDRAW_BY_ID_FAIL = 'GET_LUCKYDRAW_BY_ID_FAIL';



// CompanyFill action types
export const GET_COMPANYFILL_BY_ID_REQ = 'GET_COMPANYFILL_BY_ID_REQ';
export const GET_COMPANYFILL_BY_ID_SUCCESS = 'GET_COMPANYFILL_BY_ID_SUCCESS';
export const GET_COMPANYFILL_BY_ID_FAIL = 'GET_COMPANYFILL_BY_ID_FAIL';


// actionTypes.js

// Constants for updating LuckyDraw status
export const UPDATE_LUCKYDRAW_STATUS_REQ = 'UPDATE_LUCKYDRAW_STATUS_REQ';
export const UPDATE_LUCKYDRAW_STATUS_SUCCESS = 'UPDATE_LUCKYDRAW_STATUS_SUCCESS';
export const UPDATE_LUCKYDRAW_STATUS_FAIL = 'UPDATE_LUCKYDRAW_STATUS_FAIL';


// Constants for fetching all lucky draws
export const GET_ALL_LUCKYDRAW_REQ = 'GET_ALL_LUCKYDRAW_REQ';
export const GET_ALL_LUCKYDRAW_SUCCESS = 'GET_ALL_LUCKYDRAW_SUCCESS';
export const GET_ALL_LUCKYDRAW_FAIL = 'GET_ALL_LUCKYDRAW_FAIL';
// constants.js

// Constants for pushing ID to result
export const PUSH_TO_RESULT_REQ = 'PUSH_TO_RESULT_REQ';
export const PUSH_TO_RESULT_SUCCESS = 'PUSH_TO_RESULT_SUCCESS';
export const PUSH_TO_RESULT_FAIL = 'PUSH_TO_RESULT_FAIL';


// Constants for fetching history
export const GET_HISTORY_REQ = 'GET_HISTORY_REQ';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAIL = 'GET_HISTORY_FAIL';



// Constants for fetching result
export const GET_RESULT_REQ = 'GET_RESULT_REQ';
export const GET_RESULT_SUCCESS = 'GET_RESULT_SUCCESS';
export const GET_RESULT_FAIL = 'GET_RESULT_FAIL';





export const FILL_FAQ_FORM_REQ = 'FILL_FAQ_FORM_REQUEST';
export const FILL_FAQ_FORM_SUCCESS = 'FILL_FAQ_FORM_SUCCESS';
export const FILL_FAQ_FORM_FAIL = 'FILL_FAQ_FORM_FAIL';



export const FILL_COMPANY_FORM_REQUEST = 'FILL_COMPANY_FORM_REQUEST';
export const FILL_COMPANY_FORM_SUCCESS = 'FILL_COMPANY_FORM_SUCCESS';
export const FILL_COMPANY_FORM_FAIL = 'FILL_COMPANY_FORM_FAIL';


// Constants for fetching company forms
export const GET_COMPANY_FORM_REQ = 'GET_COMPANY_FORM_REQ';
export const GET_COMPANY_FORM_SUCCESS = 'GET_COMPANY_FORM_SUCCESS';
export const GET_COMPANY_FORM_FAIL = 'GET_COMPANY_FORM_FAIL';


// Constants for updating company form status
export const UPDATE_COMPANY_FORM_STATUS_REQ = 'UPDATE_COMPANY_FORM_STATUS_REQ';
export const UPDATE_COMPANY_FORM_STATUS_SUCCESS = 'UPDATE_COMPANY_FORM_STATUS_SUCCESS';
export const UPDATE_COMPANY_FORM_STATUS_FAIL = 'UPDATE_COMPANY_FORM_STATUS_FAIL';

// Constants for fetching company forms
export const GET_ALL_COMPANY_FORM_REQ = 'GET_ALL_COMPANY_FORM_REQ';
export const GET_ALL_COMPANY_FORM_SUCCESS = 'GET_ALL_COMPANY_FORM_SUCCESS';
export const GET_ALL_COMPANY_FORM_FAIL = 'GET_ALL_COMPANY_FORM_FAIL';




// Constants for pushing Company ID to result
export const PUSH_COMPANY_TO_RESULT_REQ = 'PUSH_COMPANY_TO_RESULT_REQ';
export const PUSH_COMPANY_TO_RESULT_SUCCESS = 'PUSH_COMPANY_TO_RESULT_SUCCESS';
export const PUSH_COMPANY_TO_RESULT_FAIL = 'PUSH_COMPANY_TO_RESULT_FAIL';



// Constants for getting all isAllow
export const GET_ALL_ISALLOW_REQ = "GET_ALL_ISALLOW_REQ";
export const GET_ALL_ISALLOW_SUCCESS = "GET_ALL_ISALLOW_SUCCESS";
export const GET_ALL_ISALLOW_FAIL = "GET_ALL_ISALLOW_FAIL";



// Constants for getting "Is Allow" pagination results
export const GET_IS_ALLOW_PP_RESULT_REQUEST = "GET_IS_ALLOW_PP_RESULT_REQUEST";
export const GET_IS_ALLOW_PP_RESULT_SUCCESS = "GET_IS_ALLOW_PP_RESULT_SUCCESS";
export const GET_IS_ALLOW_PP_RESULT_FAILURE = "GET_IS_ALLOW_PP_RESULT_FAILURE";


// Constants for creating Company Allotment
export const CREATE_COMPANY_ALLOTMENT_REQ = 'CREATE_COMPANY_ALLOTMENT_REQ';
export const CREATE_COMPANY_ALLOTMENT_SUCCESS = 'CREATE_COMPANY_ALLOTMENT_SUCCESS';
export const CREATE_COMPANY_ALLOTMENT_FAIL = 'CREATE_COMPANY_ALLOTMENT_FAIL';



// Constants for fetching User Allotment
export const GET_ALLOTMENT_REQ = 'GET_ALLOTMENT_REQ';
export const GET_ALLOTMENT_SUCCESS = 'GET_ALLOTMENT_SUCCESS';
export const GET_ALLOTMENT_FAIL = 'GET_ALLOTMENT_FAIL';



// Constants for fetching User Allotment by ID
export const GET_ALLOTMENT_BY_ID_REQ = 'GET_ALLOTMENT_BY_ID_REQ';
export const GET_ALLOTMENT_BY_ID_SUCCESS = 'GET_ALLOTMENT_BY_ID_SUCCESS';
export const GET_ALLOTMENT_BY_ID_FAIL = 'GET_ALLOTMENT_BY_ID_FAIL';



// Constants for submitting Sign Value
export const SUBMIT_SIGN_VALUE_REQ = 'SUBMIT_SIGN_VALUE_REQ';
export const SUBMIT_SIGN_VALUE_SUCCESS = 'SUBMIT_SIGN_VALUE_SUCCESS';
export const SUBMIT_SIGN_VALUE_FAIL = 'SUBMIT_SIGN_VALUE_FAIL';


// Constants for creating Individual Allotment Letter
export const CREATE_INDIVIDUAL_ALLOTMENT_REQ = 'CREATE_INDIVIDUAL_ALLOTMENT_REQ';
export const CREATE_INDIVIDUAL_ALLOTMENT_SUCCESS = 'CREATE_INDIVIDUAL_ALLOTMENT_SUCCESS';
export const CREATE_INDIVIDUAL_ALLOTMENT_FAIL = 'CREATE_INDIVIDUAL_ALLOTMENT_FAIL';
