export const ADD_SITE_REQUEST = 'ADD_SITE_REQUEST';
export const ADD_SITE_SUCCESS = 'ADD_SITE_SUCCESS';
export const ADD_SITE_FAIL = 'ADD_SITE_FAIL';


export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';

export const GET_ONGOING_SITE_REQUEST = 'GET_ONGOING_SITE_REQUEST';
export const GET_ONGOING_SITE_SUCCESS = 'GET_ONGOING_SITE_SUCCESS';
export const GET_ONGOING_SITE_FAIL = 'GET_ONGOING_SITE_FAIL';

export const GET_UPCOMING_SITE_REQUEST = 'GET_UPCOMING_SITE_REQUEST';
export const GET_UPCOMING_SITE_SUCCESS = 'GET_UPCOMING_SITE_SUCCESS';
export const GET_UPCOMING_SITE_FAIL = 'GET_UPCOMING_SITE_FAIL';

export const GET_TESTIMONIAL_SITE_REQUEST = 'GET_TESTIMONIAL_SITE_REQUEST';
export const GET_TESTIMONIAL_SITE_SUCCESS = 'GET_TESTIMONIAL_SITE_SUCCESS';
export const GET_TESTIMONIAL_SITE_FAIL = 'GET_TESTIMONIAL_SITE_FAIL';

export const GET_SITE_BY_ID_REQUEST = 'GET_SITE_BY_ID_REQUEST';
export const GET_SITE_BY_ID_SUCCESS = 'GET_SITE_BY_ID_SUCCESS';
export const GET_SITE_BY_ID_FAIL = 'GET_SITE_BY_ID_FAIL';


// actionTypes.js

export const GET_FORM_BY_ID_REQUEST = 'GET_FORM_BY_ID_REQUEST';
export const GET_FORM_BY_ID_SUCCESS = 'GET_FORM_BY_ID_SUCCESS';
export const GET_FORM_BY_ID_FAIL = 'GET_FORM_BY_ID_FAIL';



// Constants for different states of searching for sites
export const GET_SEARCHED_SITE_REQ = 'GET_SEARCHED_SITE_REQ'; // Request initiated
export const GET_SEARCHED_SITE_SUCCESS = 'GET_SEARCHED_SITE_SUCCESS'; // Request succeeded
export const GET_SEARCHED_SITE_FAIL = 'GET_SEARCHED_SITE_FAIL'; // Request failed




// Constants for getting sites by state and city
export const GET_SITE_BY_STATE_CITY_REQ = 'GET_SITE_BY_STATE_CITY_REQ';     // Request initiated
export const GET_SITE_BY_STATE_CITY_SUCCESS = 'GET_SITE_BY_STATE_CITY_SUCCESS'; // Request succeeded
export const GET_SITE_BY_STATE_CITY_FAIL = 'GET_SITE_BY_STATE_CITY_FAIL';   // Request failed
